# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener: true
    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener:  true
    exception:
        flatten_exception_format: 'rfc7807'
        map_exception_codes: true
        codes:
            'InvalidArgumentException': 400
        messages:
            'InvalidArgumentException': true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', prefer_extension: false, fallback_format: json, priorities: [ json, xml ] }
            - { path: '^/', stop: true } # Available for version >= 1.5
