nelmio_api_doc:
    documentation:
        openapi: '3.0.0'
        info:
            title: WP Data Dashboard
            description: WP Data Dashboard API
            version: '%app.version%'

    areas: # to filter documented areas
        path_patterns:
            - ^/api((?!/doc$)(?!/auth/helper)) # Accepts routes under /api except /api/doc, /api/auth/helper
        name_patterns:
            - ^(?!api_notfound) # Accepts all routes except api_notfound

