twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        appVersion: '%app.version%'
        navService: '@App\Service\NavigationService'
        pageMetaService: '@App\Service\PageMetaService'

when@test:
    twig:
        strict_variables: true
